# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('QB', 'QB'), ('WR', 'WR'), ('RB', 'RB'), ('TE', 'TE'), ('DEF', 'DEF')], max_length=8)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
            ],
        ),
        migrations.AddField(
            model_name='draftpick',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Player'),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Team'),
        ),
    ]
