# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('QB', 'QB'), ('WR', 'WR'), ('RB', 'RB'), ('TE', 'TE'), ('DEF', 'DEF')], max_length=8)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('nfl_team', models.CharField(max_length=8)),
                ('bye_week', models.IntegerField()),
                ('standard_dev', models.FloatField()),
                ('nerd_rank', models.FloatField()),
                ('nerd_position_rank', models.FloatField()),
                ('nerd_overall_rank', models.FloatField()),
                ('nerd_id', models.IntegerField()),
                ('nerd_estimated_points', models.IntegerField()),
                ('completions', models.IntegerField()),
                ('passing_attempts', models.IntegerField()),
                ('passing_yards', models.IntegerField()),
                ('passing_tds', models.IntegerField()),
                ('rush_attempts', models.IntegerField()),
                ('rush_yards', models.IntegerField()),
                ('rush_tds', models.IntegerField()),
                ('fumbles', models.IntegerField()),
                ('receptions', models.IntegerField()),
                ('receiving_yards', models.IntegerField()),
                ('receiving_tds', models.IntegerField()),
                ('sacks', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('fumble_recoveries', models.IntegerField()),
                ('def_tds', models.IntegerField()),
                ('special_team_tds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
            ],
        ),
        migrations.AddField(
            model_name='draftpick',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Player'),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Team'),
        ),
    ]
