# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nerd_overall_rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='nerd_position_rank',
            field=models.IntegerField(),
        ),
    ]
