# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_auto_20170823_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='passing_attempts',
            new_name='pass_attempts',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='passing_tds',
            new_name='pass_interceptions',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='passing_yards',
            new_name='pass_tds',
        ),
        migrations.AddField(
            model_name='player',
            name='pass_yards',
            field=models.IntegerField(null=True),
        ),
    ]
