# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_auto_20170823_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('passing_yard', models.FloatField(null=True)),
                ('pass_td', models.FloatField(null=True)),
                ('interception', models.FloatField(null=True)),
                ('rushing_yard', models.FloatField(null=True)),
                ('rush_td', models.FloatField(null=True)),
                ('reception', models.FloatField(null=True)),
                ('receiving_yard', models.FloatField(null=True)),
                ('receiving_td', models.FloatField(null=True)),
                ('fumble', models.FloatField(null=True)),
                ('def_sack', models.FloatField(null=True)),
                ('def_interception', models.FloatField(null=True)),
                ('def_fumble_recovery', models.FloatField(null=True)),
                ('def_td', models.FloatField(null=True)),
                ('special_team_td', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='draftpick',
            name='position',
        ),
        migrations.AddField(
            model_name='draftpick',
            name='estimated_points',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='draft.Team'),
        ),
        migrations.AddField(
            model_name='draft',
            name='scoring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='draft.Scoring'),
        ),
    ]
